---
- name: stop concourse web
  service:
    name: concourse-web
    state: stopped
  become: yes
  when: concourse_web_service is defined and concourse_web

- name: stop concourse worker
  service:
    name: concourse-worker
    state: stopped
  become: yes
  when: concourse_worker_service is defined and concourse_worker

- name: restart concourse web
  service:
    name: concourse-web
    state: restarted
  become: yes
  when: concourse_web_service is defined and concourse_web and concourse_service_enabled and concourse_service_start

- name: restart concourse worker
  pause:
    seconds: 10
  notify:
    - restart concourse worker after pause

- name: restart concourse worker after pause
  service:
    name: concourse-worker
    state: restarted
  become: yes
  when: concourse_worker_service is defined and concourse_worker and concourse_service_enabled and concourse_service_start

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes
